FROM python:3.12-alpine
RUN apk add --no-cache git docker-cli docker-compose curl gnupg && \
    curl -sL https://cli.doppler.com/install.sh | sh
RUN pip install --no-cache-dir fastapi "uvicorn[standard]"
RUN git config --global --add safe.directory /workspace
WORKDIR /workspace
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "5001"]
